eps1lon/dom-accessibility-api

- sources/accessible-name.ts
See https://w3c.github.io/aria/#textbox
> internal: textbox is not an abstract role

- README.md
- tests/cypress/integration/web-platform-test.js
- tests/wpt-jsdom/to-run.yaml
One test case was malformed which caused in a false negative. Fixed due to https://github.com/web-platform-tests/wpt/pull/19807
> test: Update wpt tests

- sources/__tests__/accessible-name.js
Some tests to check that byRole + accessible name can replace a lot of queries
> test: Test testing-lib integration

- sources/__tests__/accessible-name.js
- sources/__tests__/getRole.js
- sources/accessible-name.ts
- sources/getRole.ts
Also fixes `<legend />` not being considered having the `legend` role.
> feat: Consider all cases of "name from content"

- sources/__tests__/accessible-name.js
Add coverage for:
* isHTML(Select|Textarea)Element
* value of textbox when HTMLInputElement
> test: Increase coverage

- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
Implements https://w3c.github.io/aria/#namefromprohibited
> feat(name): Consider prohibited naming

- azure-pipelines.yml
See https://developercommunity.visualstudio.com/content/problem/949162/pipeline-not-run-on-pr-push.html?childToView=949241#comment-949241
> chore(ci): Fix azure not running

- .codesandbox/ci.json
Using https://codesandbox.io/docs/ci
> chore: Build PRs in CodeSandbox CI

- .changeset/pink-lizards-push.md
- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
- sources/util.ts
Fix for the bug described here: https://github.com/testing-library/dom-testing-library/issues/576
> fix: Legend element as accessible name for Fielset element

- azure-pipelines.yml
Will later be used to include a diff of the published files
> test(ci): Publish tarball as artifact

- .changeset/strange-hotels-build.md
- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
- sources/util.ts
Fix for https://github.com/testing-library/dom-testing-library/issues/570
Closes #100
> fix: Consider caption element of table

- .changeset/neat-carrots-sell.md
- README.md
- package.json
- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
- tests/cypress/integration/web-platform-test.js
- tests/wpt-jsdom/to-run.yaml
Fixes https://github.com/testing-library/dom-testing-library/issues/591
> fix: Concatenate text nodes without space

- .changeset/polite-apricots-wink.md
- README.md
- azure-pipelines.yml
Node 13 has reached its end-of-life.
> feat: Drop node 13

- .eslintrc
- sources/util.ts
Goes from 5 to 0 lint *warnings*.
> test: Fix lint warnings

- LICENSE.md
> docs: Create LICENSE.md

- .github/workflows/release.yml
Created an npm automation token and added it to secrets. 
`changesets publish` does not fail if there's nothing to publish.
> Implement release automation

- azure-pipelines.yml
> test: Run with node 15

- azure-pipelines.yml
Planned cleanup of #464 after `main` succeeded.
> test: fail if tarball cant be restored in node 15

- azure-pipelines.yml
Follow-up to https://github.com/eps1lon/dom-accessibility-api/pull/606
> test: fail if node 16 tarball diff fails

- azure-pipelines.yml
> test: Drop node 10

- yarn.lock
Ref: https://github.com/advisories/GHSA-79jw-6wg7-r9g4
> chore: Fix GHSA-79jw-6wg7-r9g4

- tests/wpt-jsdom/wpt-config.json
Unclear why we hadn't checked out `master` but some PR branch.
> test: Bump web-platform-tests

- azure-pipelines.yml
Node 15 has reached its end-of-life
> test: Drop node 15 from test matrix

- .babelrc.js
- .changeset/curly-ghosts-sing.md
- sources/__tests__/is-inaccessible.js
- sources/index.ts
- sources/is-inaccessible.ts
Copied from https://github.com/testing-library/dom-testing-library/blob/a2a3212f97fac0aae25ae352fcef19b5f3144147/src/role-helpers.js
> feat: Implement isInaccessible and isSubtreeInaccessible

- .changeset/seven-hounds-carry.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
Fixes https://github.com/testing-library/dom-testing-library/issues/1059
> fix: Compute name from author for `menu` role

- azure-pipelines.yml
- Introduce 18
- drop 12 (6 days early)
> test: Update Node.js test matrix

- .codesandbox/ci.json
Follow-up to https://github.com/eps1lon/dom-accessibility-api/pull/829
Required for https://github.com/eps1lon/dom-accessibility-api/pull/834
> Build in CodeSandbox CI with Node 14

- .github/workflows/release.yml
- azure-pipelines.yml
Follow-up to https://github.com/eps1lon/dom-accessibility-api/pull/829
> Run release with Node 14

- azure-pipelines.yml
> test: Drop Node 17 from test matrix

- sources/__tests__/accessible-description.js
- sources/__tests__/accessible-name.js
Matchers provide a better stack trace when a test fails.
And they can be understood by jest/expect-expect
> test: Use custom matchers instead of test helpers
