- README.md
- sources/accessible-name.ts
- tests/cypress/integration/web-platform-test.js
Only supported in browser. jsdom does not support before/after in getComputedStyle
`name_test_case_659-manual` and `name_test_case_660-manual` are not following spec IMO.
Some passes are due to concatenating content with whitespace which violates the spec.
> feat: Consider content from before and after pseudo elements

- sources/__tests__/getRole.js
- sources/accessible-name.ts
- sources/getRole.ts
- sources/index.ts
aria-query seems unmaintained (no response in a month). It includes some bugs and is based on an outdated mechanism (rdf is dropped from ARIA).
> feat: Fork elementToRole from aria-query

- sources/accessible-name.ts
It doesn't have anything to do with the node being connect but rather if the node is a `Document` or not.
>  If this property is used on a node that is itself a document, the value is null.
-- https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument
> chore: Get correct window if node is a Document

- sources/accessible-name.ts
We can't call the actual algorithm recursively since this removes the notion of a root node.
> chore: Remove unused options for public method

- sources/accessible-name.ts
Function was already present (but unused). Seems trivial but without using a named function I would add a comment.
> chore: Use named function for presentational check

- sources/accessible-name.ts
Commit that added it (2da473717768a945ed250a685304183c488c65f2) does not include the fixed test. Testing which one it is.
IMO the `menu` should be considered since it is a 
>  descendant of a native host language text alternative element
Ref: https://github.com/w3c/accname/issues/67
> chore: Document label descendant confusion

- .changeset/lemon-pets-cover.md
- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
`window.getComputedStyle` is very expensive. To address performance concerns this PR allows mocking this function out. 
One could mock a fake implementation that returns always visible elements. The neat part is that is puts users with and without visual impairment on the same level. If your test makes assertions about elements that are visually hidden then even sighted users won't be able to perform it.
Another use case would be wrapping `window.getComputedStyle` with a caching provider. It's unclear if we should allow providing a factory instead so that cache busting is easier (simply clear it before every call) or if this is responsibility in userland. Either way a factory option can be added later and I want to see usage first.
> feat: Allow mocking getComputedStyle

- .browserslistrc
- .changeset/tasty-shrimps-juggle.md
- .gitignore
- README.md
- azure-pipelines.yml
- package.json
- sources/accessible-name.ts
- sources/core-js-pure.d.ts
- tsconfig.json
- yarn.lock
Closes #140
Reasons this wasn't caught:
No test suite for ES5 environments and since I only use this for react `Array.from` (for testing libraries) and `Set` is already polyfilled
> feat: Support ES5 environments

- .changeset/clean-hounds-shop.md
- sources/__tests__/accessible-name.js
- sources/accessible-name.ts
Fixes `<label for>` being ignored for `<select>` and `<textarea>`
> fix: support <label> for select and textarea

- package.json
- yarn.lock
Applies https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
"Create automated security update" had no effect.
> fix: Bump vulnerable dependencies

- .babelrc.js
- .codesandbox/ci.json
- .gitignore
- azure-pipelines.yml
- package.json
- tests/build/fixtures/kcd-rollup/.gitignore
- tests/build/fixtures/kcd-rollup/README.md
- tests/build/fixtures/kcd-rollup/package.json
- tests/build/fixtures/kcd-rollup/rollup.config.js
- tests/build/fixtures/kcd-rollup/src/index.js
- yarn.lock
replaces interop cjs.
Most if this code is so that it works with the kcd-scripts rollup config when building for UMD. I don't know why that one uses cjs.
> feat: export mjs and cjs

- .babelrc.js
- .changeset/serious-tables-deny.md
- azure-pipelines.yml
- package.json
- sources/accessible-name.ts
- sources/polyfills/SetLike.ts
- sources/polyfills/array.from.ts
- tests/build/fixtures/node-es-modules/README.md
- tests/build/fixtures/node-es-modules/index.js
- tests/build/fixtures/node-es-modules/package.json
- yarn.lock
> fix: Use relative paths in exports field

- tests/build/fixtures/kcd-rollup/package.json
kcd-scripts fails if it doesn't find `@babel/runtime` in the dependencies.
> test: fix kcd-scripts fixture

- package.json
- yarn.lock
I'll miss the (almost) `kind-of` bingo.
> chore: fix security vuln in dev dependencies

- azure-pipelines.yml
- tests/build/fixtures/ava-ts-node/package.json
- tests/build/fixtures/ava-ts-node/test.ts
- tsconfig.json
Trying reproduce https://github.com/eps1lon/dom-accessibility-api/pull/168#issuecomment-608168905.
Either this isn't the same setup or this was fixed in the meantime. @jamiebuilds Do you still have issues with `dom-accessibility-api`?
> test: Add build test for ava+ts-node

- .changeset/many-waves-hear.md
- package.json
Older bundlers still need the `module` field. `exports` is for new one.
Hopefully fixes https://github.com/eps1lon/dom-accessibility-api/pull/168#issuecomment-608168905
> feat: Add module field

- .changeset/afraid-chefs-melt.md
- azure-pipelines.yml
Node 14 had its initial release. Until October 2020 we need to make sure this library is compatible.
>  test: Run with node 14

- .changeset/five-pillows-sing.md
- sources/accessible-name.ts
The name for this method was inappropriate anyway (`queryChildNodes` when it considered owned elements). Realized the spec never mentions owned elements in the name computation of children so it seems safe to remove.
> chore: document wpt vs accname conflict concerning child nodes

- .changeset/unlucky-pumas-deliver.md
- sources/util.ts
- more robust against disconnected nodes
- improve type safey
> fix(refactor): Use nodeType and tagName for element type checks

- .changeset/poor-ways-film.md
- .eslintrc
- azure-pipelines.yml
- sources/accessible-name.ts
- for-of to `.forEach` or basic for loop
- `array.push(...otherArray)` to `push.apply(array, otherArray)`
- add a CI task that prints the diff of the published package
> feat: reduce transpilation helpers

- azure-pipelines.yml
Seems like `reportDirectory` is redundant. Might be the reason for this warning.
> chore: Fix azure publish code coverage warning

- .changeset/nine-masks-begin.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
- sources/util.ts
```html
<svg>
<title>My SVG</title>
</svg>
```
Computing the name for this svg would have returned an empty string previously. It now correctly computes `My SVG` following the [accessible object in the accessibility tree for rendered SVG elements](https://www.w3.org/TR/svg-aam-1.0/#include_elements).
Closes https://github.com/testing-library/dom-testing-library/issues/685
> Consider `<title>` for the name of its `<svg>` element.

- sources/__tests__/accessible-description.js
- sources/__tests__/accessible-name.js
- sources/__tests__/helpers/test-utils.js
Makes it later easier to reason about `afterEach` order.
> test: Remove side-effects from helper utils

- sources/accessible-name-and-description.ts
- sources/getRole.ts
- sources/util.ts
- move eslint disable explainer into same line as disable directive (possible since eslint 7)
- Remove unnnecessary non-null assertion
> chore: Cleanup non-null assertions

- .changeset/young-kangaroos-clap.md
- .eslintrc
- sources/accessible-name-and-description.ts
- sources/getRole.ts
- sources/util.ts
`localName` is oftentimes what we actually want and oftentimes faster. `tagName` is usually computed from the `localName`. The living standard even hints at that by recommending user-agents to cache `tagName` internally: 
>  User agents could optimize qualified name and HTML-uppercased qualified name by storing them in internal slots.
-- https://dom.spec.whatwg.org/#concept-element-qualified-name
> feat: Use localName when available

- .changeset/witty-cycles-pay.md
- package.json
- scripts/jest/jest.base.config.js
- scripts/jest/jest.setup.js
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
- tests/cypress/support/index.js
- yarn.lock
Apparently there's value in logging errors for unsupported pseudo elements but not **every** CSS property non of which are computed correctly.
`userAgent` sniffing is not viable since that can be configured.
> feat: Ignore before/after pseudo elements in JSDOM

- .changeset/gentle-lamps-perform.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
fix #393 
If the title is empty ( I have trimmed the text ) it is not considered as accessibility name.
I hope to have done something right :)
> fix: accessibility name when title is empty

- .changeset/empty-frogs-attend.md
- .eslintrc
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
- sources/util.ts
I don't think in 
> if the current node's native markup provides an attribute (e.g. title) or element (e.g. HTML label) that defines a text alternative
an order was implied but rather deferred to host specific specs such as `html-aam`. 
Closes #405 
That section of the code is still  quite messy but working.
> fix: consider value attribute before localized input type

- .changeset/light-ladybugs-destroy.md
- sources/__tests__/getRole.js
- sources/getRole.ts
- browsers will treat an image with missing alt as an image.
- null alt is different than empty string: empty string removes the node from the AOM, where missing (null) alt does not.
- this change may impact tests that incorrectly rely on missing alt and `alt=''` being equivalent.
- recommend a patch level release.
[fixes #429]
> fix: img with missing alt should have role img

- azure-pipelines.yml
The azure dashboard is a bit busy if the pipeline fails before Cypress started. Parsing what fails is quite difficult since it contains ~40% noise.
We only attempt to publish the screenshots if they were actually created. This is potentially problematic if they erroneously weren't created but then we'll see it in the pipeline. If we never notice then it's indicative we don't need them.
> test: Publish cypress screenshots only if exists

- .changeset/plenty-crabs-pump.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
- sources/util.ts
Correctly determine accessible name when element contains a slot.
Previously, computing the accessible name would only examine child nodes. However, content placed in a slot is is an assigned node, not a child node. If an element is a slot, we now examine either assignedNodes (if content was placed in the slot) or childNodes (the default content of the slot).
Fixes #423
> fix: determine accname for elements with slots

- package.json
When searching on https://www.npmjs.com/ the results include name and description. If no description is provided it uses the first lines from the README which is unreadable because it includes all the badges.
> docs: Add description for npm

- azure-pipelines.yml
Looks like builds are not considered for DownloadPipelineArtifact because of the ubuntu-latest warning. Otherwise I can't explain why the task can't find builds.
> test: Prevent ubuntu-20.04 warning

- .github/workflows/codeql-analysis.yml
Hopefully resolves https://github.com/eps1lon/dom-accessibility-api/runs/2489513480
Should at least resolve 
> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
-- https://github.com/eps1lon/dom-accessibility-api/actions/runs/805788014
> test: Fix CodeQL action

- .changeset/ninety-suits-applaud.md
- sources/getRole.ts
```diff
-const [item] = list;
+const item = list[0];
```
Also switched from implicit non-null assertion to explicit one.
> fix: Ensure certain babel helpers aren't required

- .changeset/pretty-tigers-brake.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
- sources/util.ts
Reported in https://github.com/testing-library/dom-testing-library/issues/940
> fix: Use label attribute for naming of `<optgroup>`

- .codesandbox/ci.json
codesandbox still uses node 10 even though it reached EOL
> chore: Use node 12 in codesandbox/ci

- .changeset/breezy-garlics-trade.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
Originally reported in https://github.com/testing-library/dom-testing-library/issues/866
> fix: Consider `<label />` when computing the accessible name of `<output />`

- .github/renovate.json
I thought this worked like dependabot i.e. I comment with "automergePrComment" and renovate merges. But the comment is meant for other automation toosl
> chore(renovate): Remove pr-comment

- .changeset/small-chairs-fly.md
- sources/__tests__/getRole.js
- sources/getRole.ts
https://www.w3.org/TR/html-aria/#el-input-number
This one was missing from the implementation/tests, so I went ahead and added it.
> fix: `input[type="number"]` maps to `[role="spinbutton"]`

- .changeset/modern-carpets-ring.md
- sources/getRole.ts
- sources/util.ts
Fixes #733 
`./getRole.ts` and `./util.ts` were importing each other, causing a circular dependency. This causes a warning when using this package (or packages that depend on this like `@testing-library/jest-dom`) at least when using Rollup.
To remove the warning I moved `getLocalName` to `getRole` and re-exported it from `util` so it is still available when importing from `./util`).
> fix: Remove circular dependency

- .changeset/twelve-icons-dance.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
Closes https://github.com/eps1lon/dom-accessibility-api/issues/810
> fix: Prefer button subtree over `title` attribute

- .changeset/violet-cooks-promise.md
- sources/__tests__/accessible-description.js
- sources/__tests__/accessible-name.js
- sources/util.ts
Partially addresses #768. Fixes `aria-labelledby` and `aria-describedby` in the following situation:
1. The two elements in question (i.e. the element with `aria-*edby` and the element referenced by that attribute) are both located in the same shadow root.
2. The text contents of the second element are fully contained within its own DOM (not its shadow DOM).
I've added two tests to confirm the behavior as well.
> fix: Follow aria-labelledby and aria-describedby if they point to elements in the same shadow root

- .changeset/clever-masks-film.md
- sources/__tests__/accessible-name.js
- sources/accessible-name-and-description.ts
Closes https://github.com/eps1lon/dom-accessibility-api/issues/892
Closes https://github.com/eps1lon/dom-accessibility-api/discussions/101
> fix: Ignore `title` in 2E

- .github/workflows/release.yml
<details>
<summary>(Hopefully) fixed warnings</summary>
[Prepare or publish release](https://github.com/eps1lon/dom-accessibility-api/actions/runs/3816291228/jobs/6491830203)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: changesets/action@master
[Prepare or publish release](https://github.com/eps1lon/dom-accessibility-api/actions/runs/3816291228/jobs/6491830203#step:5:8)
The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
[Prepare or …
> chore: Pin release workflow actions to Major

- .changeset/rare-cycles-nail.md
- sources/__tests__/is-disabled.js
- sources/index.ts
- sources/is-disabled.ts
- sources/util.ts
This was discussed in https://github.com/testing-library/dom-testing-library/pull/1221#discussion_r1147913695
I wasn't sure where's the right place to put this one, please let me know if there's a better place for this and I'll change (I thought about creating a new file but didn't want to make a mess).
Thanks!
> feat: add an isDisabled function to identify whether elements are disabled or not

- .changeset/two-eagles-peel.md
- sources/__tests__/accessible-description.js
- sources/accessible-description.ts
- sources/getRole.ts
Fixes #726 
Adding `aria-description` as a valid way to describe elements, while maintaining `aria-describedby` precedence.
REF: https://w3c.github.io/aria/#aria-description
> feat: support aria-description as descriptor

- .changeset/yellow-poems-cry.md
- sources/__tests__/accessible-description.js
- sources/__tests__/accessible-name.js
- sources/__tests__/getRole.js
- sources/accessible-name-and-description.ts
- sources/accessible-name.ts
- sources/getRole.ts
- sources/util.ts
Fixes #932
Adding equivalent behaviours for the role of `"none"` where there is existing precedent for how to deal with the `"presentation"` role.
REF: https://rawgit.com/w3c/aria/stable/#none
> feat: support `"none"` role as a synonym for the `"presentation"` role

- .changeset/tame-ravens-whisper.md
- package.json
The question and answer [here](https://stackoverflow.com/questions/72457791/typescript-packages-that-ship-with-mjs-and-d-ts-but-without-d-mts-how-to-i) describes the situation in detail and is exactly identical to the current situation in the `dom-accessibility-api` package.
**In short, TypeScript modules which are marked as `type: "module"` with `moduleResolution: "node16"` cannot consume this package because while an explicit entrypoint is specified for esm (`./dist/index.mjs`), there is no corresponding typings file.** In this case, TypeScript will look for such a typings file at the location `./dist/index.d.mts` by default, and this file does not exist.
The simplest fix for this, which is the entirety of my PR, is to provide a hint to TypeScript that types should _always_ be resolved …
> Add explicit typings location to support use in TypeScript ESM modules

- .changeset/four-humans-repair.md
- package.json
Flagged by https://publint.dev/dom-accessibility-api@0.6.2
/cc @hiebj
> Ensure types are declared first in `exports` field
